# Generated by Django 3.2.3 on 2023-03-27 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_collection', '0001_initial'),
        ('Share', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shared_data',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shared_user', to='data_collection.data'),
        ),
    ]
