# Generated by Django 3.2.3 on 2023-03-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=64)),
                ('unique_id', models.CharField(default=None, max_length=64)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
