# Generated by Django 3.2.3 on 2023-03-27 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_company_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shared_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_code', models.CharField(default=None, max_length=64)),
                ('last_viewed', models.DateTimeField(blank=True, default=None, null=True)),
                ('company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_company', to='company.company')),
            ],
        ),
    ]
